- name: Ensure directory is present
  file:
    state: directory
    path: "{{ param_dest | dirname  }}"
    mode: "0655"
    recurse: yes
  become: true

- name: "Copy file from $HOME/{{ param_src }} to {{ param_dest }}"
  copy:
    src: "~/{{ param_src }}"
    dest: "{{ param_dest }}"
    mode: "0655"
  become: true

