- include_role:
    name: command_available
  vars:
    param_command: sdk

- include_role:
    name: shell_exec
  vars:
    param_cmd: "curl -s https://get.sdkman.io | bash"
  when: "not command_available"

