- name: Add apt key for yarn
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  become: true

- name: Add apt repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
  become: true

- name: Install yarn
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - yarn
  become: true

