- name: "Download package {{ param_url }}"
  get_url:
    url: "{{ param_url }}"
    dest: "/tmp/{{ param_name }}.deb"
    mode: "0644"

- name: "Install package"
  apt:
    deb: "/tmp/{{ param_name }}.deb"
    state: present
  become: true

