#!/bin/bash
set -e

# output title line with seperator
output_step() {
    cols=$(tput cols)
    printf "$(tput setaf 10)🚀 %s $(tput sgr0)" "$1"
    printf "%-`expr $cols - 5 - ${#1}`s\n" "" | tr ' ' '-'
}

# util to check if command is executable
check_cmd_present() {
    command -v "$1" > /dev/null 2>&1
    return $?
}

# linbe break
line_br() {
    echo ""
}

# helper for asking y/n
ask() {
  message=$1

  read -r -p "$(tput setaf 6)🤔 $message [y/n] $(tput sgr0)" -n 1
  echo ""

  if [[ ! $REPLY =~ ^[Yy]$ ]];
  then
        return 1
  fi

  return 0
}
output_step "Loading class"
class=$(yadm config local.class)

if [ -z "$class" ]
then
    if ask "You got no class set, do you want to set one?"
    then
        read class
        yadm config local.class "$class"
    fi
fi
echo "Class $class loaded!"
line_br

if [[ "$OSTYPE" == "darwin"* ]]
then
    output_step "MacOS detected, executing macos bootstrap"
    source ~/.config/yadm/bootstrap.macos
else
    version=$(cat /etc/issue | cut -d\\ -f1 | tail -2 | head -1  | xargs)
    echo $version
    if [[ "$version" == "Ubuntu"* ]]
    then
        output_step "Ubuntu $version detected, executing ubuntu bootstrap"
        source ~/.config/yadm/bootstrap.ubuntu
    fi
fi

output_step "Setup repos"
git clone https://github.com/timo-reymann/ssh-knock-interceptor.git $HOME/.ssh-knock-interceptor || true
line_br

output_step "Decrypt secrets"
yadm decrypt
line_br

