- name: "Check if command '{{ param_command  }}' can be found"
  shell: "command -v {{ param_command }} > /dev/null 2>&1"
  register: command_available_execution
  ignore_errors: true

- set_fact:
    command_available: "{{ command_available_execution.rc == 0 }}"

- debug:
    msg: "command_available={{ command_available }}"

