- name: "Download installer for version {{ param_version }}"
  get_url:
    url: "https://files.teamspeak-services.com/releases/client/{{ param_version }}/TeamSpeak3-Client-linux_amd64-{{ param_version  }}.run"
    dest: /tmp/ts3_client_installer.run
    mode: 777
  become: true
