- name: Install libsecret packages
  apt:
    name:
      - libsecret-1-0
      - libsecret-1-dev
  become: true

- name: Run make
  make:
    chdir: /usr/share/doc/git/contrib/credential/libsecret
  become: true

