- include_role:
    name: command_available
  vars:
    param_command: dive

- include_role:
    name: remote_deb_install
  vars:
    param_name: dive
    param_url: "https://github.com/wagoodman/dive/releases/download/v{{ param_version }}/dive_{{ param_version }}_linux_amd64.deb"
  when: "not command_available"

