#!/bin/bash
source ~/.local/share/bash-tui-toolkit/bundle.bash
DEFAULT_ENV_FILE=".env"
ENV_FILE=$1

if [ -z "$1" ]
then
    ENV_FILE=$DEFAULT_ENV_FILE
fi

if [ ! -f "$ENV_FILE" ]
then
    show_error "File does not exist" >&2
else
    export $(cat "$ENV_FILE" | sed 's/#.*//g' | xargs)
    show_success "Env file loaded"
fi
