#!/bin/bash
DEFAULT_ENV_FILE=".env"
ENV_FILE=$1

if [ -z "$1" ]
then
    ENV_FILE=$DEFAULT_ENV_FILE
fi

if [ ! -f "$ENV_FILE" ]
then
    echo "File does not exist" >&2
fi

export $(cat $ENV_FILE | sed 's/#.*//g' | xargs)

