#!/bin/bash
source ~/.local/share/bash-tui-toolkit/bundle.bash

if [[ -z "$1"  ]] || [[ -z "$2"  ]]
then
    show_error "Usage: `basename $0` <vault-file-path> <string-to-encrypt>"
    exit 2
fi

ansible-vault encrypt_string --vault-password-file $1 <<< $2
