#!/bin/bash
source ~/.local/share/bash-tui-toolkit/bundle.bash
# Helper for commiting all changes in the current directory, prefixing the directory name

if [ -z "$1" ]
then
    show_error "Please specifiy a commit message!"
    exit 2
fi

git stage .
git commit -m "$(basename $PWD): $@"

