#!/bin/bash
set +x
source ~/.local/share/bash-tui-toolkit/bundle.bash
UUID=$(cat /proc/sys/kernel/random/uuid)

# check if first parameter is there
if [ -z "$1" ]; then
    show_error "Usage: $0 <file-path|extension>"
    exit 2
fi

# create buffer with editor or use existing file
if [ -f "$1" ]; then
    file="$1"
    extension="${file##*.}"
    if [[ "$extension" == "$file" ]]; then
        extension=""
    else
        extension=".${extension}"
    fi
    delete_source=0
else
    file="/tmp/${UUID}.${1}"
    extension=".$1"
    delete_source=1
    $EDITOR "$file"
    show_success "Created file with language '$1'"
fi

if [ ! -f "$file" ]
then
    show_error "Aborted gist creation"
    exit 3
fi

# get file extension and create random name for paste
cat "$file" | gh gist create -w -f "${UUID}${extension}"

if [[ "$delete_source" -eq "1" ]]; then
    rm "$file"
    show_success "Deleted temporary file for gist"
fi

wait
