#!/bin/bash
set +x
source ~/.local/share/bash-tui-toolkit/bundle.bash
uuid()
{
    local N B T

    for (( N=0; N < 16; ++N ))
    do
        B=$(( $RANDOM%255 ))

        if (( N == 6 ))
        then
            printf '4%x' $(( B%15 ))
        elif (( N == 8 ))
        then
            local C='89ab'
            printf '%c%x' ${C:$(( $RANDOM%${#C} )):1} $(( B%15 ))
        else
            printf '%02x' $B
        fi

        for T in 3 5 7 9
        do
            if (( T == N ))
            then
                printf '-'
                break
            fi
        done
    done

    echo
}
UUID="$(uuid)"

# check if first parameter is there
if [ -z "$1" ]; then
    show_error "Usage: $0 <file-path|extension>"
    exit 2
fi

# create buffer with editor or use existing file
if [ -f "$1" ]; then
    file="$1"
    extension="${file##*.}"
    if [[ "$extension" == "$file" ]]; then
        extension=""
    else
        extension=".${extension}"
    fi
    delete_source=0
else
    file="/tmp/${UUID}.${1}"
    extension=".$1"
    delete_source=1
    $EDITOR "$file"
    show_success "Created file with language '$1'"
fi

if [ ! -f "$file" ]
then
    show_error "Aborted gist creation"
    exit 3
fi

# get file extension and create random name for paste
cat "$file" | gh gist create -w -f "${UUID}${extension}"

if [[ "$delete_source" -eq "1" ]]; then
    rm "$file"
    show_success "Deleted temporary file for gist"
fi

wait
