#!/bin/bash
#
# Helper script to download latest release artifact for github repo
#
source ~/.local/share/bash-tui-toolkit/bundle.bash
if [ -z "$1" ] || [ -z "$2" ]
then
    show_error "Usage: <username/repo> <artifcatPart to grep>";
    exit 1
fi

download_link=`curl --silent "https://api.github.com/repos/${1}/releases/latest" \
    | grep "$2" \
    | cut -d : -f 2,3 \
    | tr -d \"`

echo "Download from ${download_link} ..."
wget --quiet -O "$2" -q $download_link

if [ -f "$2" ]
then
    show_success "Downloaded relase to ${PWD}/${2}"
else
    show_error "Failed to download release"
fi
