#!/bin/bash
#
# Helper script to download latest release artifact for github repo
#

if [ -z "$1" ] || [ -z "$2" ]
then
    echo "❌ Usage: <username/repo> <artifcatPart to grep>";
    exit 1
fi

download_link=`curl --silent "https://api.github.com/repos/${1}/releases/latest" \
    | grep "$2" \
    | cut -d : -f 2,3 \
    | tr -d \"`

echo "Download from ${download_link} ..."
wget --quiet -O "$2" -q $download_link

if [ -f "$2" ]
then
    echo "✔️ Downloaded relase to ${PWD}${2}"
else
    echo "❌ Failed to download release"
fi
