#!/bin/bash
# Simple helper to fix utf8 and m$ linebreaks

if [ -z "$1" ] || [ ! -e "$1" ]
then
    echo "❌ Please specify a valid file to fix!"
    exit 2
fi

iconv -t UTF-8 "$1" -o "$1" &> /dev/null && \
dos2unix "$1" &> /dev/null &&
echo "✔️  Fixed charset and m$ bullshit!"

if [ $? != 0 ]
then
    echo "❌ Error processing file ..."
fi

