#!/bin/bash
# Simple helper to fix utf8 and m$ linebreaks
source ~/.local/share/bash-tui-toolkit/bundle.bash

if [ -z "$1" ] || [ ! -e "$1" ]
then
    show_error "Please specify a valid file to fix!"
    exit 2
fi

iconv -t UTF-8 "$1" -o "$1" &> /dev/null && \
dos2unix "$1" &> /dev/null &&
show_success "Fixed charset and m$ bullshit!"

if [ $? != 0 ]
then
    show_error "Error processing file ..."
fi

