- include_role:
    name: command_available
  vars:
    param_command: google-chrome

- include_role:
    name: remote_deb_install
  vars:
    param_name: google-chrome
    param_url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
  when: "not command_available"

