- include_role:
    name: command_available
  vars:
    param_command: anydesk

- include_role:
    name: remote_deb_install
  vars:
    param_name: anydesk
    param_url: "https://download.anydesk.com/linux/anydesk_{{ param_version }}_amd64.deb"
  when: "not command_available"
