- name: Add apt key
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    state: present
  become: true
- name: Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://cli.github.com/packages stable main"
    state: present
  become: true
- name: Install gh cli package
  apt:
    name: gh
    update_cache: true
    state: present
  become: true
