- name: Add apt repository
  apt_repository:
    repo: ppa:lutris-team/lutris
    state: present
  become: true

- name: Install lutris using apt
  apt:
    update_cache: yes
    name: lutris
    state: present
  become: true

