- name: Setup workstation
  hosts: localhost
  vars:
    qsync_version: "1.0.4.1302"
    keeweb_version: "1.13.2"
  roles:
    - role: ubuntu_ppa
      param_name: git-core/ppa
      tags:
        - packages
        - common
        - ppa

    - role: package_install
      param_packages:
        - neofetch
        - vim
        - htop
        - tilix
        - flameshot
        - gpg
        - make
        - git
      tags:
        - packages
        - common

    - role: libsecret-git
      tags:
        - packages
        - common
        - libsecret

    - role: vim_customization
      tags:
        - vim
        - common
        - editor

    - role: bashmarks
      tags:
        - bashmarks
        - common

    - role: qnap_qsync
      param_version: "{{ qsync_version }}"
      tags:
        - packages
        - common
        - qsync

    - role: keeweb
      param_version: "{{ keeweb_version }}"
      tags:
        - packages
        - common
        - keeweb

    - role: google_chrome
      tags:
        - packages
        - common
        - google-chrome

    - role: snap
      tags:
        - snap
        - common
      param_names:
        - peco

    - role: anydesk
      tags:
        - common
        - packages
        - anydesk
      param_version: "5.5.4-1"
