- name: Setup workstation
  hosts: localhost
  vars:
    qsync_version: "1.0.4.1302"
    keeweb_version: "1.13.2"
  roles:
    - role: package_install
      param_packages:
        - neofetch
        - vim
        - htop
        - tilix
        - flameshot
        - gpg
      tags:
        - packages
        - common

    - role: vim_customization
      tags:
        - vim
        - common
        - editor

    - role: bashmarks
      tags:
        - bashmarks
        - common

    - role: qnap_qsync
      param_version: "{{ qsync_version }}"
      tags:
        - packages
        - common
        - qsync

    - role: keeweb
      param_version: "{{ keeweb_version }}"
      tags:
        - packages
        - common
        - keeweb

    - role: google_chrome
      tags:
        - packages
        - common
        - google-chrome

