- name: Setup cinnamon desktop and common programs
  hosts: localhost
  roles:
    - role: ubuntu_ppa
      param_name: "agornostal/ulauncher"
      tags:
        - packages
        - desktop
        - ppa

    - role: package_install
      param_packages:
        - cinnamon
        - lightdm
        - plank
        - ulauncher
        - snapd
        - arc-theme
        - lightdm-gtk-greeter
      tags:
        - packages
        - desktop

    - role: snap
      param_names:
        - spotify
        - vlc
      tags:
        - packages
        - desktop
        - snaps

    - role: shell_exec
      param_cmd: "gsettings set org.cinnamon.desktop.default-applications.terminal exec 'tilix'"
      tags:
        - packages
        - desktop
    - role: unilaunch
      tags:
        - packages
        - desktop

