- name: Setup workstation
  hosts: localhost
  roles:
    - role: package_install
      param_packages:
        - neofetch
        - vim
        - htop
        - tilix
      tags:
        - packages
        - common

    - role: package_install
      param_packages:
        - cinnamon
      tags:
        - packages
        - desktop

    - role: shell_exec
      param_cmd: "gsettings set org.cinnamon.desktop.default-applications.terminal exec 'tilix'"
      tags:
        - packages
        - desktop

    - role: vim_customization
      tags:
        - vim
        - common
        - editor

    - role: bashmarks
      tags:
        - bashmarks
        - common
