- include_role:
    name: command_available
  vars:
    param_command: wishlist

- include_role:
    name: remote_deb_install
  vars:
    param_name: keeweb
    param_url: "https://github.com/charmbracelet/wishlist/releases/download/v{{ param_version }}/wishlist_{{ param_version }}_linux_amd64.deb"
  when: "not command_available"

