- include_role:
    name: command_available
  vars:
    param_command: unilaunch

- include_role:
    name: remote_deb_install
  vars:
    param_name: anydesk
    param_url: "https://github.com/timo-reymann/UniLaunch/releases/download/{{ param_version }}/UniLaunch-amd64.deb"
  when: "not command_available"

