- include_role:
    name: ubuntu_ppa
  vars:
    param_name: "ondrej/php"

- include_role:
    name: package_install
  vars:
    param_packages:
      - "php{{ param_version }}"
      - "php{{ param_version }}-pdo"
      - "php{{ param_version }}-zip"
      - "php{{ param_version }}-mysql"
      - "php{{ param_version }}-common"
      - "php{{ param_version }}-curl"

