- include_role:
    name: command_available
  vars:
    param_command: mongodb-compass-community

- include_role:
    name: remote_deb_install
  vars:
    param_name: mongodb-compass-community
    param_url: "https://downloads.mongodb.com/compass/mongodb-compass_{{ compass_version }}_amd64.deb"
  when: "not command_available"

