hotkeys:
  shell: {}
  profile: {}
  new-tab:
    - - Ctrl-T
terminal:
  colorScheme:
    name: Argonaut
    foreground: '#fffaf4'
    background: '#0e1019'
    cursor: '#ff0018'
    colors:
      - '#232323'
      - '#ff000f'
      - '#8ce10b'
      - '#ffb900'
      - '#008df8'
      - '#6d43a6'
      - '#00d8eb'
      - '#ffffff'
      - '#444444'
      - '#ff2740'
      - '#abe15b'
      - '#ffd242'
      - '#0092ff'
      - '#9a5feb'
      - '#67fff0'
      - '#ffffff'
  font: Ubuntu Mono
  ligatures: false
  background: theme
  cursor: beam
  environment: {}
  frontend: hterm
  bell: 'off'
  rightClick: menu
  fontSize: 17
ssh: {}
appearance:
  theme: Compact
  tabsLocation: top
  opacity: 0.45
  frame: thin
  dock: 'off'
enableAnalytics: false
enableWelcomeTab: false
titleControl:
  replacePattern: ''
