hotkeys:
  shell: {}
  profile: {}
  new-tab:
    - - Ctrl-T
  zoom-in:
    - - 'Ctrl-]'
  zoom-out:
    - - Ctrl-/
  tab-1:
    - - Ctrl-1
  tab-2:
    - - Ctrl-2
  tab-3:
    - - Ctrl-3
  tab-4:
    - - Ctrl-4
  tab-5:
    - - Ctrl-5
  tab-6:
    - - Ctrl-6
  tab-7:
    - - Ctrl-7
  tab-8:
    - - Ctrl-8
  tab-9:
    - - Ctrl-9
  next-tab:
    - - Ctrl-Tab
  previous-tab: []
  ctrl-c: []
terminal:
  colorScheme:
    name: deep
    foreground: '#cdcdcd'
    background: '#000000'
    cursor: '#d0d0d0'
    colors:
      - '#000000'
      - '#d11600'
      - '#37c32c'
      - '#e3c421'
      - '#5c6bfd'
      - '#dd5be5'
      - '#6eb4f2'
      - '#e0e0e0'
      - '#535353'
      - '#f4152c'
      - '#01ea10'
      - '#ffee1d'
      - '#8cb0f8'
      - '#e056f5'
      - '#67ecff'
      - '#f4f4f4'
  font: Ubuntu Mono
  ligatures: false
  background: colorScheme
  cursor: beam
  environment: {}
  frontend: hterm
  bell: 'off'
  rightClick: menu
  fontSize: 18
appearance:
  theme: Compact
  tabsLocation: top
  opacity: 0.4
  frame: thin
  dock: 'off'
enableAnalytics: false
enableWelcomeTab: false
titleControl:
  replacePattern: \t
pluginBlacklist:
  - ssh
ssh: {}
