hotkeys:
  shell: {}
  profile: {}
  new-tab:
    - - Ctrl-T
  zoom-in:
    - - 'Ctrl-]'
  zoom-out:
    - - Ctrl-/
  tab-1:
    - - Ctrl-1
  tab-2:
    - - Ctrl-2
  tab-3:
    - - Ctrl-3
  tab-4:
    - - Ctrl-4
  tab-5:
    - - Ctrl-5
  tab-6:
    - - Ctrl-6
  tab-7:
    - - Ctrl-7
  tab-8:
    - - Ctrl-8
  tab-9:
    - - Ctrl-9
  next-tab:
    - - Ctrl-Tab
  previous-tab: []
  ctrl-c: []
terminal:
  colorScheme:
    name: Argonaut
    foreground: '#fffaf4'
    background: '#0e1019'
    cursor: '#ff0018'
    colors:
      - '#232323'
      - '#ff000f'
      - '#8ce10b'
      - '#ffb900'
      - '#008df8'
      - '#6d43a6'
      - '#00d8eb'
      - '#ffffff'
      - '#444444'
      - '#ff2740'
      - '#abe15b'
      - '#ffd242'
      - '#0092ff'
      - '#9a5feb'
      - '#67fff0'
      - '#ffffff'
  font: Ubuntu Mono
  ligatures: false
  background: theme
  cursor: beam
  environment: {}
  frontend: hterm
  bell: 'off'
  rightClick: menu
  fontSize: 17
ssh: {}
appearance:
  theme: Compact
  tabsLocation: top
  opacity: 0.45
  frame: thin
  dock: 'off'
enableAnalytics: false
enableWelcomeTab: false
titleControl:
  replacePattern: ''
