ruleSets:
- name: Workday evening
  rules:
  - startRange: 20:00
    endRange: 12:00
    ruleName: time
  - daysOfWeekToRun:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    ruleName: week-day
- name: Weekend
  rules:
  - daysOfWeekToRun:
    - Saturday
    - Sunday
    ruleName: week-day
- name: Always
  rules:
  - ruleName: always
targets:
- executable: /usr/bin/discord
  arguments: 
  targetType: executable
  name: Discord
  waitForNetworkConnectivity: false
- executable: /usr/bin/spotify
  arguments: 
  targetType: executable
  name: Spotify
  waitForNetworkConnectivity: false
entries:
- ruleSetName: Workday evening
  targetName: Discord
- ruleSetName: Weekend
  targetName: Discord
- ruleSetName: Always
  targetName: Spotify
connectivityCheck:
  endpoint: https://connectivity-check.timo-reymann.de/
  timeout: 00:00:03
